server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ["http://172.26.209.218:9200","http://172.26.209.218:9201","http://172.26.209.218:9202"]
xpack.monitoring.ui.container.elasticsearch.enabled: true